name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    env:
      IPHONEOS_DEPLOYMENT_TARGET: 17.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get

      - name: Remove old Pods and lockfiles
        run: rm -rf Pods Podfile.lock Runner.xcworkspace
        working-directory: ios

      - name: Install CocoaPods
        run: pod install --repo-update
        working-directory: ios

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign --no-simulator

      - name: Prepare IPA Payload
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app into Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
